name: CI Pipeline

on: push

jobs:
  project-testing:
    runs-on: ubuntu-latest

    env:  # ✅ Set DAGSHUB_PAT globally so it's available to all steps
      DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4  # ✅ Use latest v4 for Python setup
        with:
          python-version: '3.10'
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run DVC pipeline
        run: |
          dvc repro

      - name: Run model tests
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: |
          python -m unittest tests/test_model.py

      - name: Promote model to production
        if: success()
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: python Scripts/promote_model.py

      - name: Run Flask app tests
        if: success()
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: python -m unittest tests/test_flask_app.py

      - name: Login to AWS ECR
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 248268265118.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t firstecr .

      - name: Tag Docker image
        run: |
          docker tag firstecr:latest 248268265118.dkr.ecr.ap-south-1.amazonaws.com/firstecr:latest
      - name: Push docker image to the ECR
        run: |
            docker push 248268265118.dkr.ecr.ap-south-1.amazonaws.com/firstecr:latest
